export default {
  name: "NAMASPA",
  subtitle: "Yoga & Massage",
  tagline: "Come as you are. Awaken your inner greatness.",
  city: "Bend, OR",
  logoMark: "N",
  logoUrl: "https://static.wixstatic.com/media/55d4a1_159facb22a1546fa9b692841a3f10350~mv2.png/v1/fill/w_149,h_150,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/nyc_circle_logo_edited.png",
  accent: "#2d7a5e",
  accentLight: "#e8f4ee",
  displayFont: "Libre Baskerville",
  classCount: "60+",
  teacherCount: "8",
  memberTier: "Monthly Unlimited",
  features: [
  { title: "Class Scheduling", desc: "Weekly schedule with real-time reservations" },
  { title: "Practice Tracking", desc: "Reflections, streaks, and milestone badges" },
  { title: "Community Feed", desc: "Member milestones and celebrations" },
  { title: "Teacher Profiles", desc: "Bios, certifications, and specialties" },
  { title: "Membership Tiers", desc: "6 plans from intro to unlimited" },
  { title: "Events & Workshops", desc: "Sound baths, trainings, and retreats" },
  { title: "Smart Notifications", desc: "Class reminders and streak alerts" },
  { title: "Admin Dashboard", desc: "Full analytics, CRM, and broadcast tools" },
  ],
  salesCards: [
  { title: "Admin Dashboard", desc: "Tap the shield icon in the app header to access the full admin suite — analytics, member CRM, scheduling, and broadcast tools." },
  { title: "Built for NAMASPA Yoga & Massage", desc: "Custom-designed for Bend's Best of Bend winner — Power Flow, Vin/Yin, Sound Baths, 200-hour teacher trainings, massage, and the Gift of Greatness guest pass program." },
  { title: "All-in-One Platform", desc: "Handles booking, payments, and member management natively — no third-party software needed." },
  { title: "Member Engagement", desc: "Practice streaks, milestone badges, guest passes, and a community feed keep members connected between classes." },
  { title: "Custom Branded", desc: "Your brand, your colors, your identity — deployed as a standalone app designed exclusively for your studio and members." },
  ],
};
